import styles from "./styles.module.css";
import "./global.css";
import { ReactNode } from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

interface NavProps {
  children: ReactNode;
}

export function Navbar({ children }: NavProps) {
  return <nav className={styles.navbar}>{children}</nav>;
}

export function NavLinks({ children }: NavProps) {
  return <ul className={styles.nav_links}> {children} </ul>;
}
